export const LOADING = "LOADING";
export const FAILURE = "FAILURE";

export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";

export const GET_NEWS_SUCCESS = "NEWS/GET_NEWS_SUCCESS";



